import { MoleculeIdentityConfig, MoleculeIdentityId, MoleculeCategory } from '../../types';
export type { MoleculeIdentityId, MoleculeIdentityConfig, MoleculeCategory };

const CANONICAL_MOLECULE_IDENTITIES: Record<
  | 'default'
  | 'aries'
  | 'taurus'
  | 'gemini'
  | 'cancer'
  | 'leo'
  | 'virgo'
  | 'libra'
  | 'scorpio'
  | 'sagittarius'
  | 'capricorn'
  | 'aquarius'
  | 'pisces',
  MoleculeIdentityConfig
> = {
  // =========================================================================
  // 1. DEFAULT MOLECULAR IDENTITY (Signature Landing-Page Crystal Molecule)
  // =========================================================================
  default: {
    id: 'default',
    name: 'Default',
    category: 'default',
    motif: 'Crystal Glass Molecule',
    tagline: 'Signature landing-page translucent crystal molecular visual with luminescent core',
    description: 'The signature Boring crystal molecular structure: translucent crystal nodes, glowing indigo-violet nuclei, and delicate bonding tubes with soft physics.',
    theme: {
      baseTone: '#818CF8',
      internalWispColor: '#A78BFA',
      secondaryWispColor: '#67E8F9',
      glowColor: '#4F46E5',
      specularHighlight: '#FFFFFF',
      wispStyle: 'neutral-pearl',
    },
    previewColors: ['#818CF8', '#A78BFA', '#67E8F9'],
    node: {
      sphereColor: '#818CF8',
      sphereSelectedColor: '#A78BFA',
      sphereNeighborColor: '#67E8F9',
      sphereHoveredColor: '#FFFFFF',
      emissiveColor: '#4F46E5',
      emissiveSelectedColor: '#7C3AED',
      emissiveNeighborColor: '#06B6D4',
      emissiveHoveredColor: '#6366F1',
      emissiveIntensity: 0.35,
      selectedEmissiveIntensity: 0.8,
      nucleusColor: '#4F46E5',
      nucleusSelectedColor: '#7C3AED',
      nucleusNeighborColor: '#06B6D4',
      nucleusEmissiveColor: '#4F46E5',
      nucleusEmissiveIntensity: 0.9,
      roughness: 0.1,
      metalness: 0.08,
      transmission: 0.82,
      thickness: 1.6,
      ior: 1.52,
      opacity: 0.9,
      glowColor: '#4F46E5',
      labelColor: '#FFFFFF',
      labelOutlineColor: '#0E1020',
    },
  },

  // =========================================================================
  // 2. THE 12 ZODIAC MOLECULES (PDF Pages 2-13: Cute, Smooth, Realistic 3D)
  // =========================================================================

  aries: {
    id: 'aries',
    name: 'Aries',
    category: 'zodiac',
    motif: 'Warm pearl & curved luminous wisps',
    tagline: 'Soft warm pearlescent orb with delicate curved luminous wisps',
    description: 'Smooth rounded silhouette, glossy warm pearl material, delicate curved luminous wisps and restrained warm glow.',
    theme: {
      baseTone: '#F7E5DE',
      internalWispColor: '#F9A492',
      secondaryWispColor: '#FAD4C0',
      glowColor: '#F9A492',
      specularHighlight: '#FFFFFF',
      wispStyle: 'curved-luminous',
    },
    previewColors: ['#F7E5DE', '#F9A492', '#F9A492'],
    node: {
      sphereColor: '#F5DDD5',
      sphereSelectedColor: '#F9A492',
      sphereNeighborColor: '#FAF0EB',
      sphereHoveredColor: '#FFF5F2',
      emissiveColor: '#7A3224',
      emissiveSelectedColor: '#AB3E2B',
      emissiveNeighborColor: '#522016',
      emissiveHoveredColor: '#963725',
      emissiveIntensity: 0.38,
      selectedEmissiveIntensity: 0.85,
      nucleusColor: '#F9A492',
      nucleusSelectedColor: '#FB7185',
      nucleusNeighborColor: '#E27863',
      nucleusEmissiveColor: '#FDC4B8',
      nucleusEmissiveIntensity: 0.75,
      roughness: 0.13,
      metalness: 0.09,
      transmission: 0.86,
      thickness: 1.7,
      ior: 1.48,
      opacity: 0.94,
      glowColor: '#F9A492',
      labelColor: '#FFF7F5',
      labelOutlineColor: '#240A05',
    },
  },

  taurus: {
    id: 'taurus',
    name: 'Taurus',
    category: 'zodiac',
    motif: 'Earthy pearl & botanical wisps',
    tagline: 'Soft earthy pearl orb with gentle botanical-like surface wisps',
    description: 'Earthy pearl orb with gentle botanical-like surface wisps, grounded translucent volume and soft highlights.',
    theme: {
      baseTone: '#EAECE1',
      internalWispColor: '#A7C1A8',
      secondaryWispColor: '#E2DEC7',
      glowColor: '#A7C1A8',
      specularHighlight: '#FFFFFF',
      wispStyle: 'botanical-surface',
    },
    previewColors: ['#EAECE1', '#A7C1A8', '#A7C1A8'],
    node: {
      sphereColor: '#E5E8DA',
      sphereSelectedColor: '#A7C1A8',
      sphereNeighborColor: '#EFF1E8',
      sphereHoveredColor: '#FAFBF7',
      emissiveColor: '#2D3F30',
      emissiveSelectedColor: '#456049',
      emissiveNeighborColor: '#1E2B20',
      emissiveHoveredColor: '#3A523E',
      emissiveIntensity: 0.36,
      selectedEmissiveIntensity: 0.82,
      nucleusColor: '#A7C1A8',
      nucleusSelectedColor: '#8CB18E',
      nucleusNeighborColor: '#6B8D6D',
      nucleusEmissiveColor: '#CFDEC0',
      nucleusEmissiveIntensity: 0.72,
      roughness: 0.14,
      metalness: 0.1,
      transmission: 0.85,
      thickness: 1.7,
      ior: 1.48,
      opacity: 0.94,
      glowColor: '#A7C1A8',
      labelColor: '#F7FAF7',
      labelOutlineColor: '#0E1710',
    },
  },

  gemini: {
    id: 'gemini',
    name: 'Gemini',
    category: 'zodiac',
    motif: 'Dual-color & translucent orbit wisps',
    tagline: 'Dual-color orb with two delicate translucent orbit wisps',
    description: 'Dual-color pearl volume blending delicate lavender and cyan with two fine, silky translucent orbital wisps.',
    theme: {
      baseTone: '#E2DEF4',
      internalWispColor: '#8B9FF7',
      secondaryWispColor: '#7AD1F5',
      glowColor: '#8B9FF7',
      specularHighlight: '#FFFFFF',
      wispStyle: 'dual-orbit',
    },
    previewColors: ['#E2DEF4', '#8B9FF7', '#7AD1F5'],
    node: {
      sphereColor: '#DAD6F0',
      sphereSelectedColor: '#8B9FF7',
      sphereNeighborColor: '#ECE9F7',
      sphereHoveredColor: '#F6F4FC',
      emissiveColor: '#2B326B',
      emissiveSelectedColor: '#4451AC',
      emissiveNeighborColor: '#1E234A',
      emissiveHoveredColor: '#38438E',
      emissiveIntensity: 0.38,
      selectedEmissiveIntensity: 0.86,
      nucleusColor: '#8B9FF7',
      nucleusSelectedColor: '#7AD1F5',
      nucleusNeighborColor: '#6C7FD8',
      nucleusEmissiveColor: '#C4D2FA',
      nucleusEmissiveIntensity: 0.76,
      roughness: 0.12,
      metalness: 0.08,
      transmission: 0.87,
      thickness: 1.8,
      ior: 1.48,
      opacity: 0.94,
      glowColor: '#8B9FF7',
      labelColor: '#F5F4FF',
      labelOutlineColor: '#0F1226',
    },
  },

  cancer: {
    id: 'cancer',
    name: 'Cancer',
    category: 'zodiac',
    motif: 'Watery pearl & cloud-like layers',
    tagline: 'Watery pearl orb with soft cloud-like translucent layers',
    description: 'Watery silvery-blue pearl orb with soft, cloud-like translucent internal layers and calming depth.',
    theme: {
      baseTone: '#DFEBF5',
      internalWispColor: '#8EC1E6',
      secondaryWispColor: '#D4E9F7',
      glowColor: '#8EC1E6',
      specularHighlight: '#FFFFFF',
      wispStyle: 'watery-cloud',
    },
    previewColors: ['#DFEBF5', '#8EC1E6', '#8EC1E6'],
    node: {
      sphereColor: '#D6E5F2',
      sphereSelectedColor: '#8EC1E6',
      sphereNeighborColor: '#E8F2FA',
      sphereHoveredColor: '#F4FAFE',
      emissiveColor: '#22405A',
      emissiveSelectedColor: '#36638C',
      emissiveNeighborColor: '#162C3E',
      emissiveHoveredColor: '#2C5376',
      emissiveIntensity: 0.36,
      selectedEmissiveIntensity: 0.84,
      nucleusColor: '#8EC1E6',
      nucleusSelectedColor: '#68A9D6',
      nucleusNeighborColor: '#538EB8',
      nucleusEmissiveColor: '#C2E2F7',
      nucleusEmissiveIntensity: 0.74,
      roughness: 0.11,
      metalness: 0.08,
      transmission: 0.89,
      thickness: 1.8,
      ior: 1.47,
      opacity: 0.95,
      glowColor: '#8EC1E6',
      labelColor: '#F2F8FD',
      labelOutlineColor: '#0A1724',
    },
  },

  leo: {
    id: 'leo',
    name: 'Leo',
    category: 'zodiac',
    motif: 'Warm golden pearl & inner radiance',
    tagline: 'Warm golden pearl orb with a gentle inner radiance',
    description: 'Champagne golden pearl orb with a gentle, dignified inner radiance and soft polished highlights.',
    theme: {
      baseTone: '#FAF0D7',
      internalWispColor: '#F3BE58',
      secondaryWispColor: '#FCEABF',
      glowColor: '#F3BE58',
      specularHighlight: '#FFFFFF',
      wispStyle: 'golden-radiance',
    },
    previewColors: ['#FAF0D7', '#F3BE58', '#F3BE58'],
    node: {
      sphereColor: '#F6EAC9',
      sphereSelectedColor: '#F3BE58',
      sphereNeighborColor: '#FAF4E1',
      sphereHoveredColor: '#FFFDF5',
      emissiveColor: '#614611',
      emissiveSelectedColor: '#966D1B',
      emissiveNeighborColor: '#422F0B',
      emissiveHoveredColor: '#7C5A16',
      emissiveIntensity: 0.4,
      selectedEmissiveIntensity: 0.88,
      nucleusColor: '#F3BE58',
      nucleusSelectedColor: '#E5A532',
      nucleusNeighborColor: '#C28923',
      nucleusEmissiveColor: '#FDE09A',
      nucleusEmissiveIntensity: 0.78,
      roughness: 0.13,
      metalness: 0.12,
      transmission: 0.86,
      thickness: 1.7,
      ior: 1.49,
      opacity: 0.94,
      glowColor: '#F3BE58',
      labelColor: '#FFFDF5',
      labelOutlineColor: '#241904',
    },
  },

  virgo: {
    id: 'virgo',
    name: 'Virgo',
    category: 'zodiac',
    motif: 'Mint-ivory & fine leaf texture',
    tagline: 'Clean mint-ivory orb with fine soft leaf-like texture',
    description: 'Clean mint-ivory pearl orb featuring fine, soft leaf-like organic textures and serene luminous depth.',
    theme: {
      baseTone: '#F2F7F2',
      internalWispColor: '#85C7A5',
      secondaryWispColor: '#E6F4EB',
      glowColor: '#85C7A5',
      specularHighlight: '#FFFFFF',
      wispStyle: 'mint-leaf',
    },
    previewColors: ['#F2F7F2', '#85C7A5', '#85C7A5'],
    node: {
      sphereColor: '#EAF3EA',
      sphereSelectedColor: '#85C7A5',
      sphereNeighborColor: '#F3F8F3',
      sphereHoveredColor: '#FCFDFC',
      emissiveColor: '#214734',
      emissiveSelectedColor: '#346E51',
      emissiveNeighborColor: '#163124',
      emissiveHoveredColor: '#2B5B43',
      emissiveIntensity: 0.35,
      selectedEmissiveIntensity: 0.82,
      nucleusColor: '#85C7A5',
      nucleusSelectedColor: '#68B38C',
      nucleusNeighborColor: '#4D946F',
      nucleusEmissiveColor: '#BFE7D3',
      nucleusEmissiveIntensity: 0.72,
      roughness: 0.12,
      metalness: 0.08,
      transmission: 0.88,
      thickness: 1.8,
      ior: 1.48,
      opacity: 0.94,
      glowColor: '#85C7A5',
      labelColor: '#F7FCF8',
      labelOutlineColor: '#091A11',
    },
  },

  libra: {
    id: 'libra',
    name: 'Libra',
    category: 'zodiac',
    motif: 'Lilac pearl & silky translucent bands',
    tagline: 'Balanced lilac pearl orb with two silky translucent bands',
    description: 'Balanced lilac pearl sphere with two silky, flowing translucent bands and delicate harmonic highlights.',
    theme: {
      baseTone: '#ECE4F7',
      internalWispColor: '#A78FE0',
      secondaryWispColor: '#EFE6FA',
      glowColor: '#A78FE0',
      specularHighlight: '#FFFFFF',
      wispStyle: 'silky-bands',
    },
    previewColors: ['#ECE4F7', '#A78FE0', '#A78FE0'],
    node: {
      sphereColor: '#E4DBF2',
      sphereSelectedColor: '#A78FE0',
      sphereNeighborColor: '#EFE9F7',
      sphereHoveredColor: '#FAF7FD',
      emissiveColor: '#36245C',
      emissiveSelectedColor: '#583A96',
      emissiveNeighborColor: '#24183E',
      emissiveHoveredColor: '#472F7A',
      emissiveIntensity: 0.37,
      selectedEmissiveIntensity: 0.85,
      nucleusColor: '#A78FE0',
      nucleusSelectedColor: '#8E71D4',
      nucleusNeighborColor: '#7456BA',
      nucleusEmissiveColor: '#D8CAF5',
      nucleusEmissiveIntensity: 0.75,
      roughness: 0.12,
      metalness: 0.09,
      transmission: 0.87,
      thickness: 1.8,
      ior: 1.48,
      opacity: 0.94,
      glowColor: '#A78FE0',
      labelColor: '#FAF7FD',
      labelOutlineColor: '#160B29',
    },
  },

  scorpio: {
    id: 'scorpio',
    name: 'Scorpio',
    category: 'zodiac',
    motif: 'Deep violet & luminous sweep',
    tagline: 'Deep violet pearl orb with one soft smoky luminous sweep',
    description: 'Deep violet pearl orb traversed by a soft smoky luminous sweep, creating mysterious depth and presence.',
    theme: {
      baseTone: '#3B294F',
      internalWispColor: '#B17FE6',
      secondaryWispColor: '#804FB3',
      glowColor: '#B17FE6',
      specularHighlight: '#FFFFFF',
      wispStyle: 'smoky-sweep',
    },
    previewColors: ['#3B294F', '#B17FE6', '#B17FE6'],
    node: {
      sphereColor: '#3F2C54',
      sphereSelectedColor: '#B17FE6',
      sphereNeighborColor: '#533C6B',
      sphereHoveredColor: '#6B4E8A',
      emissiveColor: '#451D6B',
      emissiveSelectedColor: '#752FB6',
      emissiveNeighborColor: '#2F134A',
      emissiveHoveredColor: '#5D2590',
      emissiveIntensity: 0.42,
      selectedEmissiveIntensity: 0.9,
      nucleusColor: '#B17FE6',
      nucleusSelectedColor: '#9B5FE0',
      nucleusNeighborColor: '#7D43BF',
      nucleusEmissiveColor: '#DFC7FB',
      nucleusEmissiveIntensity: 0.8,
      roughness: 0.15,
      metalness: 0.14,
      transmission: 0.82,
      thickness: 1.9,
      ior: 1.5,
      opacity: 0.93,
      glowColor: '#B17FE6',
      labelColor: '#F7F2FD',
      labelOutlineColor: '#190A2B',
    },
  },

  sagittarius: {
    id: 'sagittarius',
    name: 'Sagittarius',
    category: 'zodiac',
    motif: 'Cool pearl & diagonal light trail',
    tagline: 'Cool pearl orb with one graceful diagonal light trail',
    description: 'Cool periwinkle pearl sphere featuring a graceful diagonal luminous light trail with restrained atmospheric glow.',
    theme: {
      baseTone: '#E4E8F7',
      internalWispColor: '#839DE8',
      secondaryWispColor: '#D6E0FA',
      glowColor: '#839DE8',
      specularHighlight: '#FFFFFF',
      wispStyle: 'diagonal-trail',
    },
    previewColors: ['#E4E8F7', '#839DE8', '#839DE8'],
    node: {
      sphereColor: '#DBE1F2',
      sphereSelectedColor: '#839DE8',
      sphereNeighborColor: '#EAF0FA',
      sphereHoveredColor: '#F7FAFD',
      emissiveColor: '#213369',
      emissiveSelectedColor: '#3653A8',
      emissiveNeighborColor: '#162248',
      emissiveHoveredColor: '#2C4489',
      emissiveIntensity: 0.38,
      selectedEmissiveIntensity: 0.86,
      nucleusColor: '#839DE8',
      nucleusSelectedColor: '#6684DE',
      nucleusNeighborColor: '#4F6FCD',
      nucleusEmissiveColor: '#B8CBFA',
      nucleusEmissiveIntensity: 0.76,
      roughness: 0.13,
      metalness: 0.09,
      transmission: 0.87,
      thickness: 1.8,
      ior: 1.48,
      opacity: 0.94,
      glowColor: '#839DE8',
      labelColor: '#F4F7FD',
      labelOutlineColor: '#0A122E',
    },
  },

  capricorn: {
    id: 'capricorn',
    name: 'Capricorn',
    category: 'zodiac',
    motif: 'Teal mineral & curved texture',
    tagline: 'Soft teal mineral pearl orb with subtle curved texture',
    description: 'Soft teal mineral pearl orb with subtle curved texture lines, grounded structure and tranquil internal light.',
    theme: {
      baseTone: '#DBEAE7',
      internalWispColor: '#6AA89E',
      secondaryWispColor: '#D3ECE6',
      glowColor: '#6AA89E',
      specularHighlight: '#FFFFFF',
      wispStyle: 'mineral-curved',
    },
    previewColors: ['#DBEAE7', '#6AA89E', '#6AA89E'],
    node: {
      sphereColor: '#D2E3E0',
      sphereSelectedColor: '#6AA89E',
      sphereNeighborColor: '#E4F0ED',
      sphereHoveredColor: '#F5FAF9',
      emissiveColor: '#1D453F',
      emissiveSelectedColor: '#2E6E64',
      emissiveNeighborColor: '#13302B',
      emissiveHoveredColor: '#265952',
      emissiveIntensity: 0.36,
      selectedEmissiveIntensity: 0.84,
      nucleusColor: '#6AA89E',
      nucleusSelectedColor: '#53958B',
      nucleusNeighborColor: '#417B72',
      nucleusEmissiveColor: '#B4DDD6',
      nucleusEmissiveIntensity: 0.74,
      roughness: 0.14,
      metalness: 0.11,
      transmission: 0.86,
      thickness: 1.8,
      ior: 1.48,
      opacity: 0.94,
      glowColor: '#6AA89E',
      labelColor: '#F3FAF8',
      labelOutlineColor: '#091A17',
    },
  },

  aquarius: {
    id: 'aquarius',
    name: 'Aquarius',
    category: 'zodiac',
    motif: 'Aqua pearl & flowing silky wisps',
    tagline: 'Aqua pearl orb wrapped by silky flowing translucent wisps',
    description: 'Luminous aqua pearl orb smoothly wrapped by silky, flowing translucent wisps with airy crystal clarity.',
    theme: {
      baseTone: '#D6F4F5',
      internalWispColor: '#47BAC0',
      secondaryWispColor: '#BAEFF1',
      glowColor: '#47BAC0',
      specularHighlight: '#FFFFFF',
      wispStyle: 'flowing-wisps',
    },
    previewColors: ['#D6F4F5', '#47BAC0', '#47BAC0'],
    node: {
      sphereColor: '#CEF0F1',
      sphereSelectedColor: '#47BAC0',
      sphereNeighborColor: '#E2F7F8',
      sphereHoveredColor: '#F3FCFD',
      emissiveColor: '#154B4E',
      emissiveSelectedColor: '#22787D',
      emissiveNeighborColor: '#0E3335',
      emissiveHoveredColor: '#1C6266',
      emissiveIntensity: 0.38,
      selectedEmissiveIntensity: 0.86,
      nucleusColor: '#47BAC0',
      nucleusSelectedColor: '#30A4AA',
      nucleusNeighborColor: '#22858A',
      nucleusEmissiveColor: '#A1E8EC',
      nucleusEmissiveIntensity: 0.76,
      roughness: 0.11,
      metalness: 0.08,
      transmission: 0.89,
      thickness: 1.8,
      ior: 1.47,
      opacity: 0.95,
      glowColor: '#47BAC0',
      labelColor: '#F0FBFC',
      labelOutlineColor: '#071F21',
    },
  },

  pisces: {
    id: 'pisces',
    name: 'Pisces',
    category: 'zodiac',
    motif: 'Blue-pink pearl & dual flowing wisps',
    tagline: 'Blue-pink pearl orb with two gentle flowing light wisps',
    description: 'Pastel blue and blush-pink pearl gradient with two gentle, harmonious flowing light wisps floating effortlessly.',
    theme: {
      baseTone: '#E5ECF8',
      internalWispColor: '#E687B2',
      secondaryWispColor: '#7EB0EC',
      glowColor: '#D68BB8',
      specularHighlight: '#FFFFFF',
      wispStyle: 'dual-flowing',
    },
    previewColors: ['#E5ECF8', '#E687B2', '#7EB0EC'],
    node: {
      sphereColor: '#DEE7F6',
      sphereSelectedColor: '#D68BB8',
      sphereNeighborColor: '#EBF1FA',
      sphereHoveredColor: '#F7F9FD',
      emissiveColor: '#4A2A4C',
      emissiveSelectedColor: '#79437C',
      emissiveNeighborColor: '#321D34',
      emissiveHoveredColor: '#643767',
      emissiveIntensity: 0.38,
      selectedEmissiveIntensity: 0.86,
      nucleusColor: '#E687B2',
      nucleusSelectedColor: '#D46D9C',
      nucleusNeighborColor: '#B65481',
      nucleusEmissiveColor: '#FAC1D9',
      nucleusEmissiveIntensity: 0.76,
      roughness: 0.12,
      metalness: 0.08,
      transmission: 0.88,
      thickness: 1.8,
      ior: 1.48,
      opacity: 0.94,
      glowColor: '#D68BB8',
      labelColor: '#FAF4F7',
      labelOutlineColor: '#1F0B1E',
    },
  },

};

// =========================================================================
// 3. BACKWARDS-COMPATIBILITY ALIASES
// (Seamless mapping so any previously stored user profile gracefully resolves)
// =========================================================================
export const MOLECULE_IDENTITIES: Record<MoleculeIdentityId, MoleculeIdentityConfig> = {
  ...CANONICAL_MOLECULE_IDENTITIES,
  neptune: CANONICAL_MOLECULE_IDENTITIES.aquarius,
  aurora: CANONICAL_MOLECULE_IDENTITIES.pisces,
  solar: CANONICAL_MOLECULE_IDENTITIES.leo,
  crystal: CANONICAL_MOLECULE_IDENTITIES.default,
  luna: CANONICAL_MOLECULE_IDENTITIES.cancer,
  ocean: CANONICAL_MOLECULE_IDENTITIES.cancer,
  violet: CANONICAL_MOLECULE_IDENTITIES.scorpio,
  comet: CANONICAL_MOLECULE_IDENTITIES.sagittarius,
  moon: CANONICAL_MOLECULE_IDENTITIES.cancer,
  eclipse: CANONICAL_MOLECULE_IDENTITIES.scorpio,
  nebula: CANONICAL_MOLECULE_IDENTITIES.pisces,
};

/**
 * 12 Zodiac Molecule List (Ordered canonically from Aries to Pisces)
 */
export const ZODIAC_MOLECULE_LIST: MoleculeIdentityConfig[] = [
  MOLECULE_IDENTITIES.aries,
  MOLECULE_IDENTITIES.taurus,
  MOLECULE_IDENTITIES.gemini,
  MOLECULE_IDENTITIES.cancer,
  MOLECULE_IDENTITIES.leo,
  MOLECULE_IDENTITIES.virgo,
  MOLECULE_IDENTITIES.libra,
  MOLECULE_IDENTITIES.scorpio,
  MOLECULE_IDENTITIES.sagittarius,
  MOLECULE_IDENTITIES.capricorn,
  MOLECULE_IDENTITIES.aquarius,
  MOLECULE_IDENTITIES.pisces,
];

/**
 * Default Molecule
 */
export const DEFAULT_MOLECULE: MoleculeIdentityConfig = MOLECULE_IDENTITIES.default;

/**
 * Complete active molecule selection list: Default + 12 Zodiacs
 */
export const ALL_MOLECULE_LIST: MoleculeIdentityConfig[] = [
  DEFAULT_MOLECULE,
  ...ZODIAC_MOLECULE_LIST,
];

/**
 * Safe accessor for any identity ID with fallback to Default
 */
export const getMoleculeIdentity = (id?: string | null): MoleculeIdentityConfig => {
  if (!id) return DEFAULT_MOLECULE;
  const config = MOLECULE_IDENTITIES[id as MoleculeIdentityId];
  if (config) return config;
  return DEFAULT_MOLECULE;
};
